apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "clientModuleName" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "clientModuleName" . }}-selector  
  minReadySeconds: 10   
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1     
  template:
    metadata:
      labels:
        app: {{ include "clientModuleName" . }}-selector
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      imagePullSecrets:
      - name: secret-docker-auth
      containers:
      - name: {{ include "clientModuleName" . }}-container
        image: {{ include "customDockerImage" . }} 
        {{ include "resources" . }}
        volumeMounts:
          - name: {{ include "clientModuleName" . }}-openid-signing
            mountPath: "/{{ include "clientModuleName" . }}/signing"
            readOnly: true
          - name: {{ include "clientModuleName" . }}-openid-encryption
            mountPath: "/{{ include "clientModuleName" . }}/encryption"
            readOnly: true
        imagePullPolicy: Always
        ports: 
        - containerPort: {{ .Values.port }} 
        env:
        - name: ModuleName
          value: {{ include "clientModuleName" . }}
        {{ include "env_aspnetcore" .}}
        {{ include "env_logging" . }}
        {{ include "env_metadata" .}}
        {{ include "env_openidclient" .}}
        {{ include "env_custom" .}}
        {{- range .Values.customSecret -}}
        - name: {{ .name }}
          valueFrom:
           secretKeyRef:
             name: {{ include "clientModuleName" $ }}-secrets
             key: {{ .name }}
        {{ end }} 
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: {{ include "clientModuleName" . }}-secrets
              key: ConnectionStrings--ApplicationInsights
        - name: ConnectionStrings__AzureStorage
          valueFrom:
            secretKeyRef:
              name: {{ include "clientModuleName" . }}-secrets
              key: ConnectionStrings--AzureStorage 
      volumes:
        - name: {{ include "clientModuleName" . }}-openid-signing
          secret:
            secretName: {{ include "clientModuleName" . }}-openid-signing
            optional: false
        - name: {{ include "clientModuleName" . }}-openid-encryption
          secret:
            secretName: {{ include "clientModuleName" . }}-openid-encryption
            optional: false
      
      