apiVersion: v1
kind: Secret 
metadata:
  name: {{ include "clientModuleName" . }}-secrets
type: Opaque
data:  
  "ConnectionStrings--ApplicationInsights":  {{ .Values.global.connections.applicationinsights | b64enc }}
  "ConnectionStrings--AzureStorage": {{ .Values.global.connections.azurestorage | b64enc }}
  "OpenIdOptions--EncryptionPassword": {{ .Values.global.openId.encryptionPassword | b64enc }} 
  "OpenIdOptions--SigningPassword": {{ .Values.global.openId.signingPassword | b64enc }} 
  {{ range .Values.customSecret }}
  {{ .name | quote }}: {{ .value | b64enc }}
  {{ end }}