apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "clientModuleName" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "clientModuleName" . }}-selector  
  minReadySeconds: 10   
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1     
  template:
    metadata:
      labels:
        app: {{ include "clientModuleName" . }}-selector
    spec:
      imagePullSecrets:
      - name: secret-docker-auth
      containers:
      - name: {{ include "clientModuleName" . }}-container
        image: {{ include "clientDockerImage" . }}
        volumeMounts:
          - name: {{ .Release.Name }}-openid-signing
            mountPath: "/{{ .Release.Name }}/signing"
            readOnly: true
          - name: {{ .Release.Name }}-openid-encryption
            mountPath: "/{{ .Release.Name }}/encryption"
            readOnly: true
        imagePullPolicy: Always
        ports: 
        - containerPort: {{ .Values.port }} 
        env:
        - name: ModuleName
          value: {{ include "clientModuleName" . }}
        - name: AppName
          value: {{ .Values.global.Name }}
        - name: ClientName
          value: {{ .Values.name }}
        - name: ReleaseName
          value: {{ .Release.Name }}
        - name: Host
          value: {{ include "clientHost" . }}
        - name: AppVersion
          value: {{ include "appVersion" . }}
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ include "environment" . }}
        - name: Logging__Level
          value: {{ .Values.global.logging.level }} 
        {{ $counter := 0 | int }}
        {{- range .Values.global.logging.overrides -}}
        - name: Logging__{{ $counter }}__SourceContext
          value: {{ .sourceContext }}
        - name: Logging__{{ $counter }}__Level
          value: {{ .level }}
        {{ $counter = add1 $counter }}
        {{- end -}}
        {{ range .Values.customEnvironment }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{ end }}
        {{ range .Values.customSecret }}
        - name: {{ .name }}
          valueFrom:
           secretKeyRef:
             name: {{ include "clientModuleName" $ }}-secrets
             key: {{ .name }}
        {{ end }}
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:{{ .Values.port }}   
        - name: AccountClientOptions__TenantId
          value: {{ .Values.accountClientOptions.tenantId }}
        - name: AccountClientOptions__ApplicationId
          value: {{ .Values.accountClientOptions.applicationId }}
        - name: AccountClientOptions__OpenIdClientId
          value: {{ .Values.accountClientOptions.openIdClientId }}
        - name: AccountClientOptions__OpenIdClientSecret
          value: {{ .Values.accountClientOptions.openIdClientSecret }}
        - name: AccountClientOptions__OpenIdClientDomain
          value: {{ include "clientUrl" . }}
        - name: AccountClientOptions__AuthBaseUrl
          value: {{ .Values.global.openId.baseAuthUrl }}
        - name: AccountClientOptions__ApiBaseUrl
          value: {{ .Values.global.openId.baseAuthUrl }}
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: {{ include "clientModuleName" . }}-secrets
              key: ConnectionStrings--ApplicationInsights
      volumes:
        - name: {{ .Release.Name }}-openid-signing
          secret:
            secretName: {{ .Release.Name }}-openid-signing
            optional: false
        - name: {{ .Release.Name }}-openid-encryption
          secret:
            secretName: {{ .Release.Name }}-openid-encryption
            optional: false
      
      