apiVersion: v1
kind: Secret 
metadata:
  name: {{ include "clientModuleName" . }}-secrets
type: Opaque
data:   
  "ConnectionStrings--ApplicationInsights":  {{ .Values.global.connections.applicationinsights | b64enc }}
  {{ range .Values.customSecret }}
  {{ .name | quote }}: {{ .value | b64enc }}
  {{ end }}