apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata:
  name: {{ include "moduleName" . }}-clusterissuer
spec:
  acme:
    email: info@blauhaustechnology.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ include "moduleName" . }}-secret-ssl
    solvers:
    - http01:
        ingress:
          class: nginx