apiVersion: v1
kind: Secret 
metadata:
  name: {{ include "moduleName" . }}-secrets
type: Opaque
data:  
  "ConnectionStrings--EvacsDb": {{ .Values.global.connections.evacsdb | b64enc }}
  "ConnectionStrings--ApplicationInsights":  {{ .Values.global.connections.applicationinsights | b64enc }}
  "ConnectionStrings--AzureStorage": {{ .Values.global.connections.azurestorage | b64enc }}
  "SendGridApiKey": {{ .Values.global.connections.sendgrid | b64enc }} 