apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "clientModuleName" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "clientModuleName" . }}-selector  
  minReadySeconds: 10   
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1     
  template:
    metadata:
      labels:
        app: {{ include "clientModuleName" . }}-selector
    spec:
      imagePullSecrets:
      - name: secret-docker-auth
      containers:
      - name: {{ include "clientModuleName" . }}-container
        image: {{ include "clientDockerImage" . }} 
        imagePullPolicy: Always
        ports: 
        - containerPort: {{ .Values.port }} 
        env:
        - name: ModuleName
          value: {{ include "clientModuleName" . }}
        {{ include "env_aspnetcore" .}}
        {{ include "env_logging" . }}
        {{ include "env_metadata" .}}
        {{ include "env_openidserver" .}}
        {{ include "env_custom" .}}   
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: {{ include "clientModuleName" . }}-secrets
              key: ConnectionStrings--ApplicationInsights 
      
      