apiVersion: v2
name: blazor
description: Web host for blazor WASM app
version: CHART_VERSION        # version of the chart 
type: application
appVersion: "0.0.0"           # version of the application