apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "moduleName" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "moduleName" . }}-selector  
  minReadySeconds: 10   
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1     
  template:
    metadata:
      labels:
        app: {{ include "moduleName" . }}-selector
        orleans/serviceId: {{ .Release.Name }}-cluster
        orleans/clusterId: {{ .Release.Name }}-cluster
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      imagePullSecrets:
      - name: secret-docker-auth
      containers:
      - name: {{ include "moduleName" . }}-container
        image: {{ include "dockerImage" . }} 
        volumeMounts:
          - name: {{ .Release.Name }}-openid-signing
            mountPath: "/{{ .Release.Name }}/signing"
            readOnly: true
          - name: {{ .Release.Name }}-openid-encryption
            mountPath: "/{{ .Release.Name }}/encryption"
            readOnly: true
        imagePullPolicy: Always
        ports: 
        - containerPort: {{ .Values.port }} 
        - containerPort: 8000 
        - containerPort: 11111
        - containerPort: 30000
        env:
        - name: ORLEANS_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['orleans/serviceId']
        - name: ORLEANS_CLUSTER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['orleans/clusterId']
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
          value: {{ .Values.terminationGracePeriodSeconds | quote }}
        - name: ModuleName
          value: {{ include "moduleName" . }}
        - name: AppName
          value: {{ .Values.global.name }}
        - name: ReleaseName
          value: {{.Release.Name}}
        - name: Host
          value: {{ include "host" . }}
        - name: AppVersion
          value: {{ include "appVersion" . }}
        - name: Evacs__MaxJobsInParallel
          value: {{ .Values.global.evacs.maxJobsInParallel | quote }}
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ include "environment" . }}
        - name: Logging__Level
          value: {{ .Values.global.logging.level }} 
        {{ $counter := 0 | int }}
        {{- range .Values.global.logging.overrides -}}
        - name: Logging__{{ $counter }}__SourceContext
          value: {{ .sourceContext }}
        - name: Logging__{{ $counter }}__Level
          value: {{ .level }}
        {{ $counter = add1 $counter }}
        {{ end }}
        {{ range .Values.customEnvironment }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{ end }}
        {{ range .Values.customSecret }}
        - name: {{ .name }}
          valueFrom:
           secretKeyRef:
             name: {{ include "moduleName" $ }}-secrets
             key: {{ .name }}
        {{ end }}
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:{{ .Values.port }}
        - name: ASPNETCORE_HTTPS_PORT
          value: {{ .Values.port }}
        - name: OpenIdOptions__AccessTokenExpiryHours 
          value: {{ .Values.global.openId.accessTokenExpiryHours | quote }}
        - name: OpenIdOptions__RefreshTokenExpiryDays
          value: {{ .Values.global.openId.refreshTokenExpiryDays | quote }}
        - name: OpenIdOptions__BaseAuthUrl
          value: {{ .Values.global.openId.baseAuthUrl }}
        {{- range .Values.global.openId.scopes }}
        - name: OpenIdOptions__Scopes__{{ .name }}
          value: {{ .id | quote -}}
        {{ end }}
        - name: OpenIdOptions__EncryptionPassword
          valueFrom:
            secretKeyRef:
              name: {{ include "moduleName" . }}-secrets
              key: OpenIdOptions--EncryptionPassword
        - name: OpenIdOptions__SigningPassword
          valueFrom:
            secretKeyRef:
              name: {{ include "moduleName" . }}-secrets
              key: OpenIdOptions--SigningPassword
        - name: ConnectionStrings__SendGrid
          valueFrom:
            secretKeyRef:
              name: {{ include "moduleName" . }}-secrets
              key: ConnectionStrings--SendGrid
        - name: ConnectionStrings__EvacsDb
          valueFrom:
            secretKeyRef:
              name: {{ include "moduleName" . }}-secrets
              key: ConnectionStrings--EvacsDb
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: {{ include "moduleName" . }}-secrets
              key: ConnectionStrings--ApplicationInsights
        - name: ConnectionStrings__AzureStorage
          valueFrom:
            secretKeyRef:
              name: {{ include "moduleName" . }}-secrets
              key: ConnectionStrings--AzureStorage 
      volumes:
        - name: {{ .Release.Name }}-openid-signing
          secret:
            secretName: {{ .Release.Name }}-openid-signing
            optional: false
        - name: {{ .Release.Name }}-openid-encryption
          secret:
            secretName: {{ .Release.Name }}-openid-encryption
            optional: false
      
      