apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "moduleName" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "moduleName" . }}-selector  
  minReadySeconds: 10   
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1     
  template:
    metadata:
      labels:
        app: {{ include "moduleName" . }}-selector
        orleans/serviceId: {{ include "applicationName" . }}-cluster
        orleans/clusterId: {{ include "applicationName" . }}-cluster
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      imagePullSecrets:
      - name: secret-docker-auth
      containers:
      - name: {{ include "moduleName" . }}-container
        image: {{ printf "%s/%s-%s:%s" .Values.global.repository .Values.global.appName .Chart.Name .Values.global.appVersion }}
        volumeMounts:
          - name: openid-signing
            mountPath: "/etc/certificates/signing"
            readOnly: true
          - name: openid-encryption
            mountPath: "/etc/certificates/encryption"
            readOnly: true
        imagePullPolicy: Always
        ports: 
        - containerPort: {{ .Values.port }} 
        - containerPort: 8000 
        - containerPort: 11111
        - containerPort: 30000
        env:
        - name: ORLEANS_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['orleans/serviceId']
        - name: ORLEANS_CLUSTER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['orleans/clusterId']
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
          value: {{ .Values.terminationGracePeriodSeconds | quote }}
        - name: AppName
          value: {{ .Values.global.appName }}
        - name: ReleaseName
          value: {{.Release.Name}}
        - name: Host
          value: {{ include "host" . }}
        - name: AppVersion
          value: {{ include "appVersion" . }}
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ include "environment" . }}
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:{{ .Values.port }}
        - name: OpenIdOptions__AccessTokenExpiryHours 
          value: "2"
        - name: OpenIdOptions__RefreshTokenExpiryDays
          value: "14"
        - name: OpenIdOptions__BaseAuthUrl
          value: https://account-sample.blauhaustechnology.com
        {{ $counter := 0 | int }}
        {{- range .Values.global.logging -}}
        - name: Logging__{{ $counter }}__SourceContext
          value: {{ .sourceContext }}
        - name: Logging__{{ $counter }}__Level
          value: {{ .level }}
        {{ $counter = add1 $counter }}
        {{- end -}}
        - name: ConnectionStrings__EvacsDb
          valueFrom:
            secretKeyRef:
              name: {{ include "applicationName" . }}-secrets
              key: ConnectionStrings--EvacsDb
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: {{ include "applicationName" . }}-secrets
              key: ConnectionStrings--ApplicationInsights
        - name: ConnectionStrings__AzureStorage
          valueFrom:
            secretKeyRef:
              name: {{ include "applicationName" . }}-secrets
              key: ConnectionStrings--AzureStorage 
      volumes:
        - name: openid-signing
          secret:
            secretName: openid-signing
            optional: false
        - name: openid-encryption
          secret:
            secretName: openid-encryption
            optional: false
      