apiVersion: v1
kind: Secret 
metadata:
  name: {{ include "moduleName" . }}-secrets
type: Opaque
data:  
  "ConnectionStrings--EvacsDb": {{ .Values.global.connections.evacsdb | b64enc }}
  "ConnectionStrings--ApplicationInsights":  {{ .Values.global.connections.applicationinsights | b64enc }}
  "ConnectionStrings--AzureStorage": {{ .Values.global.connections.azurestorage | b64enc }}
  "ConnectionStrings--SendGrid": {{ .Values.global.connections.sendgrid | b64enc }} 
  "OpenIdOptions--EncryptionPassword": {{ .Values.global.openId.encryptionPassword | b64enc }} 
  "OpenIdOptions--SigningPassword": {{ .Values.global.openId.signingPassword | b64enc }} 
  {{- range .Values.customSecret -}}
  {{ .name | quote }}: {{ .value | b64enc -}}
  {{- end -}}