apiVersion: v1
kind: Service 
metadata:
  name: {{ include "moduleName" . }}-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}              
      targetPort: {{ .Values.port }}        
  selector:
    app: {{ include "moduleName" . }}-selector