name: Release Charts

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Set Version
        run: |
          npm install @actions/core --save
          node ./.github/scripts/getversion.js

      - name: Replace Action
        uses: datamonsters/replace-action@v2
        with:
          files: './charts/admin/Chart.yaml,./charts/api/Chart.yaml,./charts/auth/Chart.yaml'
          replacements: '$CHART_VERSION={{ VERSION_NAME }}'
      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"